apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tap-cpu-spring-petclinic
  labels:
    app.kubernetes.io/part-of: tap-cpu-spring-petclinic
    apps.tanzu.vmware.com/language: java
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/supplychain: cpu-test-scan
    apps.tanzu.vmware.com/workload-type: cpu-web
    app.kubernetes.io/component: run
    carto.run/workload-name: tap-cpu-spring-petclinic
spec:
  template:
    metadata:
      annotations:
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.6.9
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/spring-boot-actuator-probes
          spring-boot-convention/service-intent-mysql
          spring-boot-convention/service-intent-postgres
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"tap-cpu-spring-petclinic","apps.tanzu.vmware.com/language":"java","apps.tanzu.vmware.com/pipeline":"test","apps.tanzu.vmware.com/supplychain":"cpu-test-scan","apps.tanzu.vmware.com/workload-type":"cpu-web"},"name":"tap-cpu-spring-petclinic","namespace":"developer"},"spec":{"params":[{"name":"git_user_email","value":"acic.rome@gmail.com"},{"name":"git_user_name","value":"acirom"},{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"acirom"},{"name":"gitops_repository_name","value":"cpu-acic1"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/acirom/TAPspring-petclinic"}}}}
        services.conventions.apps.tanzu.vmware.com/mysql: mysql-connector-java/8.0.29
        services.conventions.apps.tanzu.vmware.com/postgres: postgresql/42.3.6
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tap-cpu-spring-petclinic
        apps.tanzu.vmware.com/language: java
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/supplychain: cpu-test-scan
        apps.tanzu.vmware.com/workload-type: cpu-web
        carto.run/workload-name: tap-cpu-spring-petclinic
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        services.conventions.apps.tanzu.vmware.com/mysql: workload
        services.conventions.apps.tanzu.vmware.com/postgres: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: tap-cpu-spring-petclinic
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: harbor.tanzu.vxlab.local/tap-project/supply-chain2/tap-cpu-spring-petclinic-developer@sha256:767f3c07b007c7ab102a9f48afc79bc3202ac852afa15de83e3c22175e2fa6f8
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

